# Generated by Django 4.2.13 on 2024-06-28 00:46

from django.db import migrations, models
import scraper_manager.models.setting_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(default=scraper_manager.models.setting_models.SourceOptions['UNKNOWN'])),
                ('username', models.CharField(max_length=255)),
                ('encrypted_password', models.CharField(max_length=255)),
            ],
        ),
    ]
