# Generated by Django 4.2.13 on 2024-06-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceconfiguration',
            old_name='username',
            new_name='email',
        ),
    ]
