# Generated by Django 4.2.13 on 2024-06-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_manager', '0002_rename_username_sourceconfiguration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceconfiguration',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sourceconfiguration',
            name='encrypted_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
