# Generated by Django 4.2.13 on 2024-06-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_manager', '0003_alter_sourceconfiguration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceconfiguration',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sourceconfiguration',
            name='encrypted_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
