# Generated by Django 4.2.13 on 2024-06-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_manager', '0004_alter_sourceconfiguration_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField()),
                ('date_posted', models.DateField()),
                ('post_title', models.CharField(max_length=255)),
            ],
        ),
    ]
