# Generated by Django 4.2.13 on 2024-07-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_manager', '0005_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='source',
        ),
    ]
