# Generated by Django 4.2.13 on 2024-07-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_manager', '0006_remove_blogpost_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('encrypted_password', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
